# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code
print(np.__version__)


1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a=np.random.random((2,3,5))
a


array([[[0.98114466, 0.20183545, 0.90934533, 0.15416095, 0.55587468],
        [0.28150791, 0.72307317, 0.68775737, 0.14849558, 0.48991022],
        [0.04716308, 0.97414832, 0.72510469, 0.31277953, 0.71913285]],

       [[0.57763884, 0.88136436, 0.32822733, 0.92877733, 0.47536758],
        [0.59704547, 0.43189618, 0.32869652, 0.93156561, 0.98632537],
        [0.92183737, 0.6248783 , 0.15510199, 0.1405606 , 0.53858996]]])

In [4]:
a=np.random.randn(2,3,5)
a

array([[[ 0.65325357,  0.26732121, -1.24938487, -0.25220591,
         -1.0531105 ],
        [ 0.03533202, -1.44507032, -0.80242477, -0.63765787,
         -1.23538821],
        [-0.62767481, -0.92270569, -1.6606164 , -0.56636537,
         -0.61009717]],

       [[ 0.11540413, -1.20403728,  0.8675952 ,  0.1209529 ,
          1.67313448],
        [-0.19768884,  0.75714395, -1.24968563, -0.04606626,
          1.08845663],
        [ 0.54747018, -1.03891266, -0.06518604, -0.22468232,
          1.2288479 ]]])

In [5]:
a= np.random.randint(27, size=(2,3,5))
a


array([[[ 9,  4,  2,  8, 21],
        [17,  9, 10, 23, 18],
        [21, 19, 20,  3, 13]],

       [[ 8, 23, 16, 22, 25],
        [22, 22, 12, 10,  1],
        [14, 16, 21, 23, 20]]])

In [6]:
a= np.random.random_sample((2,3,5))
a

array([[[0.20991522, 0.47477492, 0.80263349, 0.1286728 , 0.67683033],
        [0.849107  , 0.44402519, 0.22446931, 0.25608856, 0.53368173],
        [0.52527008, 0.64304853, 0.31134104, 0.00664285, 0.61038468]],

       [[0.24906806, 0.25255121, 0.77265281, 0.52156825, 0.78562328],
        [0.17282239, 0.64378438, 0.32433018, 0.53699961, 0.57160625],
        [0.7673771 , 0.85853807, 0.57583854, 0.73250147, 0.77019988]]])

In [7]:
# Method 3
array= np.arange(30).reshape(2,3,5)
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### 4. Print *a*.


In [8]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here
b= np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [10]:
# your code here

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here
a==b

C:\Users\Zoe Mercury\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# your answer here
a+b
#to be added they dont need to be flattened out, they just need to have the same structure

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
c= b.reshape(2,3,5)
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# because a and c have the same shape
d= a+c
d

array([[[1.20991522, 1.47477492, 1.80263349, 1.1286728 , 1.67683033],
        [1.849107  , 1.44402519, 1.22446931, 1.25608856, 1.53368173],
        [1.52527008, 1.64304853, 1.31134104, 1.00664285, 1.61038468]],

       [[1.24906806, 1.25255121, 1.77265281, 1.52156825, 1.78562328],
        [1.17282239, 1.64378438, 1.32433018, 1.53699961, 1.57160625],
        [1.7673771 , 1.85853807, 1.57583854, 1.73250147, 1.77019988]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here

# calculate the difference between a and d i.e. subtract d from a or vice versa
# d= a+c, c=1, hence a+c-a=c
print (d-a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e=a*c
e

array([[[0.20991522, 0.47477492, 0.80263349, 0.1286728 , 0.67683033],
        [0.849107  , 0.44402519, 0.22446931, 0.25608856, 0.53368173],
        [0.52527008, 0.64304853, 0.31134104, 0.00664285, 0.61038468]],

       [[0.24906806, 0.25255121, 0.77265281, 0.52156825, 0.78562328],
        [0.17282239, 0.64378438, 0.32433018, 0.53699961, 0.57160625],
        [0.7673771 , 0.85853807, 0.57583854, 0.73250147, 0.77019988]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here
e==a

#yes because c=1 (e=a*1 i.e. e=a)

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [18]:
print(d)

[[[1.20991522 1.47477492 1.80263349 1.1286728  1.67683033]
  [1.849107   1.44402519 1.22446931 1.25608856 1.53368173]
  [1.52527008 1.64304853 1.31134104 1.00664285 1.61038468]]

 [[1.24906806 1.25255121 1.77265281 1.52156825 1.78562328]
  [1.17282239 1.64378438 1.32433018 1.53699961 1.57160625]
  [1.7673771  1.85853807 1.57583854 1.73250147 1.77019988]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()




#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
# your code here
f= np.empty((2,3,5),dtype=int)
f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [22]:
f= []

for biglist in d:
    for list in biglist:
        for number in list:
            if d_min<number<d_mean:
                f.append (25)
            elif d_mean<number<d_max:
                f.append (75)
            elif number==d_mean:
                f.append (50)
            elif number==d_min:
                f.append (0)
            elif number==d_max:
                f.append (100)
                
f

[25,
 25,
 75,
 25,
 75,
 75,
 25,
 25,
 25,
 75,
 75,
 75,
 25,
 0,
 75,
 25,
 25,
 75,
 75,
 75,
 25,
 75,
 25,
 75,
 75,
 75,
 100,
 75,
 75,
 75]

In [23]:
f=np.reshape(f,(2,3,5))
f

array([[[ 25,  25,  75,  25,  75],
        [ 75,  25,  25,  25,  75],
        [ 75,  75,  25,   0,  75]],

       [[ 25,  25,  75,  75,  75],
        [ 25,  75,  25,  75,  75],
        [ 75, 100,  75,  75,  75]]])


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [25]:
# your code here

condition0= (d==d_min)
condition25= (d_min<d) & (d<d_mean)
condition50= (d==d_mean)
condition75= (d_mean<d) & (d<d_max)
condition100= (d==d_max)

f= np.where(condition0,0,f)
f= np.where(condition100,100,f)
f= np.where(condition50,50,f)
f= np.where(condition25,25,f)
f= np.where(condition75,75,f)


f


array([[[ 25,  25,  75,  25,  75],
        [ 75,  25,  25,  25,  75],
        [ 75,  75,  25,   0,  75]],

       [[ 25,  25,  75,  75,  75],
        [ 25,  75,  25,  75,  75],
        [ 75, 100,  75,  75,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
# your code here
print(d)
print(f)

[[[1.80972876 1.91010848 1.49605502 1.84960558 1.92028134]
  [1.7764113  1.01511011 1.96874994 1.5663138  1.65342559]
  [1.45326628 1.44340461 1.97997648 1.45533092 1.74195867]]

 [[1.62225791 1.01341282 1.43741717 1.57467563 1.70499465]
  [1.4305051  1.76611079 1.38669573 1.84975981 1.84442342]
  [1.46008336 1.83940907 1.89713169 1.08280854 1.24992421]]]
[[[ 75  75  25  75  75]
  [ 75  25  75  25  75]
  [ 25  25 100  25  75]]

 [[ 75   0  25  25  75]
  [ 25  75  25  75  75]
  [ 25  75  75  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [57]:
# your code here
f= [[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]

g=[]

for biglist in f:
    for list in biglist:
        for i in list:
            if i==0:
                g.append("A")
            elif i==25:
                g.append("B")
            elif i==50:
                g.append("C")
            elif i==75:
                g.append("D")
            else:
                g.append("E")
        
g2= np.array(g)
g2.reshape(2,3,5)

array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'D']],

       [['B', 'B', 'B', 'B', 'E'],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']]], dtype='<U1')