# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [24]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [25]:
# your code
# np.version
print(np.__version__)


1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [26]:
a=np.random.random((2,3,5))
a
#how to define type as int
#doesn't work: a=np.random.random((2,3,5),dtype=int) 

array([[[0.22004629, 0.08463526, 0.10070223, 0.26538508, 0.71965312],
        [0.47502737, 0.86455373, 0.84942036, 0.99778556, 0.32457776],
        [0.09218584, 0.00997538, 0.58662432, 0.38066507, 0.41201554]],

       [[0.28848729, 0.32954693, 0.06081692, 0.14377577, 0.38866902],
        [0.86674896, 0.53316083, 0.95518397, 0.34463625, 0.02776316],
        [0.92038815, 0.29912772, 0.31735228, 0.24232834, 0.94250021]]])

In [27]:
a=np.random.randn(2,3,5)
a

array([[[-0.6233454 , -1.28737415, -1.45615589,  1.33270745,
         -0.01496269],
        [-0.42240195,  0.70796415,  0.01372795, -0.23482192,
         -0.56909764],
        [ 0.23074135,  0.25368874,  1.01141062,  0.3178722 ,
          1.76094298]],

       [[ 2.02732573,  1.47973897,  0.78339996,  1.88169069,
          1.6983634 ],
        [-1.72166724, -0.47102654,  1.21905684, -0.29629502,
         -0.80673331],
        [ 0.10050232, -0.57984051, -1.09368429, -0.81280116,
          0.42285469]]])

In [28]:
a= np.random.randint(27, size=(2,3,5))
a
#do I have to define max value?

array([[[17,  5, 16, 26,  9],
        [10, 15,  5, 22,  5],
        [ 2, 16, 23,  6, 19]],

       [[20, 10,  5, 17, 11],
        [ 1, 23, 20,  5, 25],
        [ 1,  7, 23,  5, 19]]])

In [29]:
a= np.random.random_sample((2,3,5))
a

array([[[0.80972876, 0.91010848, 0.49605502, 0.84960558, 0.92028134],
        [0.7764113 , 0.01511011, 0.96874994, 0.5663138 , 0.65342559],
        [0.45326628, 0.44340461, 0.97997648, 0.45533092, 0.74195867]],

       [[0.62225791, 0.01341282, 0.43741717, 0.57467563, 0.70499465],
        [0.4305051 , 0.76611079, 0.38669573, 0.84975981, 0.84442342],
        [0.46008336, 0.83940907, 0.89713169, 0.08280854, 0.24992421]]])

In [30]:
# Method 3
array= np.arange(30).reshape(2,3,5)
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### 4. Print *a*.


In [31]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [32]:
# your code here
b= np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [33]:
# your code here

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [34]:
# your code here
a==b

C:\Users\Zoe Mercury\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [35]:
# your answer here
a+b
#to be added they dont need to be flattened out, they just need to have the same structure

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
# your code here
c= b.reshape(2,3,5)
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [38]:
# because a and c have the same shape
d= a+c
d

array([[[1.80972876, 1.91010848, 1.49605502, 1.84960558, 1.92028134],
        [1.7764113 , 1.01511011, 1.96874994, 1.5663138 , 1.65342559],
        [1.45326628, 1.44340461, 1.97997648, 1.45533092, 1.74195867]],

       [[1.62225791, 1.01341282, 1.43741717, 1.57467563, 1.70499465],
        [1.4305051 , 1.76611079, 1.38669573, 1.84975981, 1.84442342],
        [1.46008336, 1.83940907, 1.89713169, 1.08280854, 1.24992421]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [39]:
# your code/answer here

# calculate the difference between a and d i.e. subtract d from a or vice versa
# d= a+c, c=1, hence a+c-a=c
print (d-a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [59]:
# your code here
e=a*c
e

array([[[13., 23., 12., 25., 19.],
        [21.,  7., 10., 11., 25.],
        [15.,  5.,  7.,  6., 12.]],

       [[16., 14., 23., 15.,  3.],
        [20., 16., 21., 22.,  0.],
        [26., 21., 21., 16.,  3.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [60]:
# your code/answer here
e==a

#yes because c=1 (e=a*1 i.e. e=a)

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [40]:
print(d)

[[[1.80972876 1.91010848 1.49605502 1.84960558 1.92028134]
  [1.7764113  1.01511011 1.96874994 1.5663138  1.65342559]
  [1.45326628 1.44340461 1.97997648 1.45533092 1.74195867]]

 [[1.62225791 1.01341282 1.43741717 1.57467563 1.70499465]
  [1.4305051  1.76611079 1.38669573 1.84975981 1.84442342]
  [1.46008336 1.83940907 1.89713169 1.08280854 1.24992421]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [41]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

#when I leave the brackets empty, does it take all numbers from the lists into consideration?
#How is my mean equal to my max?



#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [42]:
# your code here
f= np.empty((2,3,5),dtype=int)
f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [43]:
f= []

for biglist in d:
    for list in biglist:
        for number in list:
            if d_min<number<d_mean:
                f.append (25)
            elif d_mean<number<d_max:
                f.append (75)
            elif number==d_mean:
                f.append (50)
            elif number==d_min:
                f.append (0)
            elif number==d_max:
                f.append (100)
                
f

[75,
 75,
 25,
 75,
 75,
 75,
 25,
 75,
 25,
 75,
 25,
 25,
 100,
 25,
 75,
 75,
 0,
 25,
 25,
 75,
 25,
 75,
 25,
 75,
 75,
 25,
 75,
 75,
 25,
 25]

In [44]:
f=np.reshape(f,(2,3,5))
f

array([[[ 75,  75,  25,  75,  75],
        [ 75,  25,  75,  25,  75],
        [ 25,  25, 100,  25,  75]],

       [[ 75,   0,  25,  25,  75],
        [ 25,  75,  25,  75,  75],
        [ 25,  75,  75,  25,  25]]])


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [40]:
# your code here
# I need to replace every value in f with the corresponding value from d

# if x = d_min<x<d_mean, then x=25
# if x = d_mean<x<d_max, then x=75
# if x==d_mean, then x=50
# if x==d_min, then x=0
# if x==d_max, then x=100

# print (d)
# print (d_min)
# print (d_max)
# print (d_mean)
___________________________________________________________


# f= []

# for biglist in d:
#     for list in biglist:
#         for number in list:
#             print(number)
#             if d_min<number<d_mean:
#                 f.append (number,25)
#             elif d_mean<number<d_max:
#                 f.append (number,75)
# #             elif number==d_mean:
# #                 f.append (50)
# #             elif number==d_min:
# #                 f.append (0)
# #             elif number==d_max:
# #                 f.append (100)
_____________________________________________________________________

#---------------------- Peter's solution-----------------------

# print (np.where(f==0,1,f)

# f= np.where(d==d_min,0,f)
# f= np.where(d==d_max,100,f)
# f= np.where(d==m_mean,50,f)
# f= np.where(d_min<d & d<d_mean,25,f)
# f= np.where(d_mean<d & d<d_max,75,f)

# f

condition0= (d==d_min)
condition25= (d_min<d) & (d<d_mean)
#didnt work as d_min<d & d<d_mean
condition50= (d==d_mean)
condition75= (d_mean<d) & (d<d_max)
condition100= (d==d_max)

f= np.where(condition0,0,d)
#didnt work when f was at the end
f= np.where(condition100,100,f)
f= np.where(condition50,50,f)
f= np.where(condition25,25,f)
f= np.where(condition75,75,f)
#didnt work when conditions were stated in the np.where brackets instead of defined separately

f

#why is there a d at the end in the first f=np.where...""
#why does it iterate through every number in list d without a for loop or indexing?

array([[[ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  25.,  75.]],

       [[ 75.,  75.,   0.,  75.,  25.],
        [  0.,  75.,  25.,  75.,   0.],
        [ 25.,  75.,  25., 100.,  25.]]])

In [42]:
# import numpy as np

# d = [[[1.26075862 1.64915163 1.17412605 1.75509388 1.9332088 ]
#   [1.53857153 1.13854165 1.97175781 1.32327798 1.26939958]
#   [1.43071321 1.14299739 1.26728802 1.79253045 1.61672984]]

#  [[1.74842941 1.15525644 1.54111523 1.28681006 1.77311503]
#   [1.79760024 1.89404937 1.49820193 1.23238564 1.74325924]
#   [1.32261015 1.95659874 1.99928683 1.91755833 1.98886592]]]

#how can I convert d into a numpy array?


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
# your code here
print(d)
print(f)

[[[1.80972876 1.91010848 1.49605502 1.84960558 1.92028134]
  [1.7764113  1.01511011 1.96874994 1.5663138  1.65342559]
  [1.45326628 1.44340461 1.97997648 1.45533092 1.74195867]]

 [[1.62225791 1.01341282 1.43741717 1.57467563 1.70499465]
  [1.4305051  1.76611079 1.38669573 1.84975981 1.84442342]
  [1.46008336 1.83940907 1.89713169 1.08280854 1.24992421]]]
[[[ 75  75  25  75  75]
  [ 75  25  75  25  75]
  [ 25  25 100  25  75]]

 [[ 75   0  25  25  75]
  [ 25  75  25  75  75]
  [ 25  75  75  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [57]:
# your code here
f= [[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]

g=[]

for biglist in f:
    for list in biglist:
        for i in list:
            if i==0:
                g.append("A")
            elif i==25:
                g.append("B")
            elif i==50:
                g.append("C")
            elif i==75:
                g.append("D")
            else:
                g.append("E")
        
g2= np.array(g)
g2.reshape(2,3,5)

array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'D']],

       [['B', 'B', 'B', 'B', 'E'],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']]], dtype='<U1')