# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [7]:
# your code
# np.version
print(np.__version__)


1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [41]:
a=np.random.random((2,3,5))
a
#how to define type as int

array([[[0.26075862, 0.64915163, 0.17412605, 0.75509388, 0.9332088 ],
        [0.53857153, 0.13854165, 0.97175781, 0.32327798, 0.26939958],
        [0.43071321, 0.14299739, 0.26728802, 0.79253045, 0.61672984]],

       [[0.74842941, 0.15525644, 0.54111523, 0.28681006, 0.77311503],
        [0.79760024, 0.89404937, 0.49820193, 0.23238564, 0.74325924],
        [0.32261015, 0.95659874, 0.99928683, 0.91755833, 0.98886592]]])

In [32]:
a= np.random.randint(27, size=(2,3,5))
a
#do I have to define max value?

array([[[17,  1,  1,  4,  4],
        [23,  6, 20, 24,  1],
        [ 7, 11, 18, 18,  3]],

       [[22,  6,  3, 23,  7],
        [22, 21, 24,  9, 25],
        [ 4,  0,  6,  7, 11]]])

In [ ]:
# Method 3

#### 4. Print *a*.


In [ ]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [38]:
# your code here
b= np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [ ]:
# your code here

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [39]:
# your code here
a==b

C:\Users\Zoe Mercury\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [40]:
# your answer ahere
a+b
#to be added they dont need to be flattened out, they just need to have the same structure

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [51]:
# your code here
c= b.reshape(2,3,5)
print(c)
print (a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[0.26075862 0.64915163 0.17412605 0.75509388 0.9332088 ]
  [0.53857153 0.13854165 0.97175781 0.32327798 0.26939958]
  [0.43071321 0.14299739 0.26728802 0.79253045 0.61672984]]

 [[0.74842941 0.15525644 0.54111523 0.28681006 0.77311503]
  [0.79760024 0.89404937 0.49820193 0.23238564 0.74325924]
  [0.32261015 0.95659874 0.99928683 0.91755833 0.98886592]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [53]:
# your code/answer here
d= a+c
d

array([[[1.26075862, 1.64915163, 1.17412605, 1.75509388, 1.9332088 ],
        [1.53857153, 1.13854165, 1.97175781, 1.32327798, 1.26939958],
        [1.43071321, 1.14299739, 1.26728802, 1.79253045, 1.61672984]],

       [[1.74842941, 1.15525644, 1.54111523, 1.28681006, 1.77311503],
        [1.79760024, 1.89404937, 1.49820193, 1.23238564, 1.74325924],
        [1.32261015, 1.95659874, 1.99928683, 1.91755833, 1.98886592]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [67]:
# your code/answer here
# print(a)
# print(d)
# we were supposed to calculate the difference between a and d i.e. subtract d from a or vice versa
print (d-a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [61]:
# your code here
e=a*c
e

array([[[0.26075862, 0.64915163, 0.17412605, 0.75509388, 0.9332088 ],
        [0.53857153, 0.13854165, 0.97175781, 0.32327798, 0.26939958],
        [0.43071321, 0.14299739, 0.26728802, 0.79253045, 0.61672984]],

       [[0.74842941, 0.15525644, 0.54111523, 0.28681006, 0.77311503],
        [0.79760024, 0.89404937, 0.49820193, 0.23238564, 0.74325924],
        [0.32261015, 0.95659874, 0.99928683, 0.91755833, 0.98886592]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [62]:
# your code/answer here
e==a

#yes because c=1 (e=a*1 i.e. e=a)

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [64]:
print(d)

[[[1.26075862 1.64915163 1.17412605 1.75509388 1.9332088 ]
  [1.53857153 1.13854165 1.97175781 1.32327798 1.26939958]
  [1.43071321 1.14299739 1.26728802 1.79253045 1.61672984]]

 [[1.74842941 1.15525644 1.54111523 1.28681006 1.77311503]
  [1.79760024 1.89404937 1.49820193 1.23238564 1.74325924]
  [1.32261015 1.95659874 1.99928683 1.91755833 1.98886592]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [75]:
# your code here
d_max=d.mean()
d_min=d.min()
d_mean=d.mean()

#when I leave the brackets empty, does it take all numbers from the lists into consideration?
#How is my mean equal to my max?



1.5706429664758625

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [72]:
# your code here
f= np.empty((2,3,5),dtype=int)
f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [74]:
# your code here
# if x = d_min<x<d_mean, then x=25
# if x = d_mean<x<d_max, then x=75
# if x==d_mean, then x=50
# if x==d_min, then x=0
# if x==d_max, then x=100

print (d)
print (d_min)
print (d_max)
print (d_mean)

for i in d:
    if d_min<i<d_mean:
        f.append (25)
    elif d_mean<i<d_max:
        f.append (75)
    elif x==d_mean:
        f.append (50)
    elif x==d_min:
        f.append (0)
    elif x==d_max

[[[1.26075862 1.64915163 1.17412605 1.75509388 1.9332088 ]
  [1.53857153 1.13854165 1.97175781 1.32327798 1.26939958]
  [1.43071321 1.14299739 1.26728802 1.79253045 1.61672984]]

 [[1.74842941 1.15525644 1.54111523 1.28681006 1.77311503]
  [1.79760024 1.89404937 1.49820193 1.23238564 1.74325924]
  [1.32261015 1.95659874 1.99928683 1.91755833 1.98886592]]]
1.1385416454013881
1.5706429664758625
1.5706429664758625


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here